# GET http://localhost:3000/

# POST http://localhost:3000/auth/login
# Content-Type: application/json

# {
#     "email": "pablito@gmaial.com",
#     "password": "pablito123"
# }

# POST http://localhost:3000/auth/register
# Content-Type: application/json

# {
#     "username":"matias",
#     "email": "matias@gmail.com",
#     "password": "matias"
# }

GET http://localhost:3000/auth/getUsers

# GET http://localhost:3000/product/getAll

# POST http://localhost:3000/cart/payCart